services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: 878311410723.dkr.ecr.us-east-1.amazonaws.com/portfolio-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO
    depends_on:
      - postgres
    networks:
      - portfolio-network

  frontend:
    image: 878311410723.dkr.ecr.us-east-1.amazonaws.com/portfolio-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge